### PR TITLE
Update fabric8-tenant-che version to 2.0.61

### PR DESCRIPTION
**Pull request by fabric8cd**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@fabric8cd snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-474-2`

**Comment by davidfestal** [comment]
[test]

**Comment by xcoulon** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by davidfestal** [comment]
closing since `2.0.62` has been created and merged to fix this

**Pull request closed without merging**
