### PR TITLE
Decrease minimal RAM allowed for che containers

### PR DESCRIPTION
**Pull request by riuvshin**
Decrease minimal RAM allowed for che containers
issue: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2511

/cc @ibuziuk

### CODE REVIEW

**Comment by fabric8cd** [comment]
This PR changes one or more of the template files. These changes are now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?templatesRepoBlob=10cbabf23c48ccd8428a696c9e1bba8400977340) and click the update tenant button

**Comment by fabric8cd** [comment]
This PR changes one or more of the template files. These changes are now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?templatesRepoBlob=8e11423e9e3d9132fedfdb6de30849285c96a452) and click the update tenant button

**Comment by garagatyi** [comment]
@riuvshin can we proceed with this?

**Comment by riuvshin** [comment]
@garagatyi I don't have merge permissions here :)
@MatousJobanek  can you merge this please?

**Comment by ibuziuk** [comment]
merged to master

**Pull request merged**
