### PR TITLE
docs(README) add instructions to setup platform

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Comment by sbose78** [comment]
[test]

**Comment by sbose78** [comment]
@surajssd add yourself to https://github.com/almighty/almighty-jobs/blob/master/devtools-ci-index.yaml#L12 to be able to trigger CI builds

**Comment by surajssd** [comment]
@sbose78 done https://github.com/almighty/almighty-jobs/pull/441

**Comment by aslakknutsen** [comment]
[test]

**Comment by surajssd** [comment]
[test]

**Comment by jaseemabid** [comment]
@surajssd Should I merge this? Is it still valid?

**Comment by surajssd** [comment]
@jaseemabid no I think I will close this one, come with a cleaner one!

**Pull request closed without merging**
