### PR TITLE
support configuring tenants with internal docker registry when deploy…

### PR DESCRIPTION
**Pull request by rawlingsj**
…ing to kubernetes

we deploy a private docker registry in fabric8 on kubernetes deployments, if no external registry is configured check default kubernetes service env vars

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-327-1`

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-327-2`

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
[test]

**Comment by jstrachan** [comment]
LGTM

**Pull request merged**
