### PR TITLE
Set the `JOB_ID` variable to a generated value...

### PR DESCRIPTION
**Pull request by davidfestal**
Set the `JOB_ID` variable to a generated value to do exactly what would be done by `oc process` on this
template parameter of type `generate`

Signed-off-by: David Festal <dfestal@redhat.com>

### CODE REVIEW

**Comment by fabric8cd** [comment]
@davidfestal snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-483-7`

**Comment by fabric8cd** [comment]
@davidfestal snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-483-8`

**Comment by ibuziuk** [comment]
[test]

**Comment by ibuziuk** [comment]
[test]

**Comment by fabric8cd** [comment]
@davidfestal snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-483-9`

**Pull request merged**
