### PR TITLE
Set new GitHub token endpoint for Che

### PR DESCRIPTION
**Pull request by alexeykazakov**
We need to add a new ConfigMap to tenant service before merging this PR! - Update: Done!

Fixes https://github.com/fabric8-services/fabric8-tenant/issues/414

### CODE REVIEW

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-415-2`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-415-3`

**Comment by ibuziuk** [comment]
@alexeykazakov 

`We need to add a new ConfigMap to tenant service before merging this PR!`

Do you mean https://github.com/fabric8-services/fabric8-tenant-che/pull/46 ?

**Comment by alexeykazakov** [comment]
@ibuziuk I meant auth.url config map for f8tenant service. It's already done (in houskeeping).

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-415-4`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-415-5`

**Pull request merged**
