### PR TITLE
copy the new http exposecontroller config when creating ConfigMap in …

### PR DESCRIPTION
**Pull request by rawlingsj**
…tenant namespaces

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-230-1`

**Comment by aslakknutsen** [comment]
[test]

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-230-2`

**Comment by aslakknutsen** [comment]
[test]

**Pull request merged**
