### PR TITLE
Add scripts for Jenkins

### PR DESCRIPTION
**Pull request by piyush-garg**
Add some scripts for Jenkins required to merge
the patch https://github.com/fabric8io/osio-pipeline/pull/116

Fixes https://github.com/fabric8io/osio-pipeline/issues/74

### CODE REVIEW

**Comment by fabric8cd** [comment]
This PR changes one or more of the template files. These changes are now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?templatesRepoBlob=36aa519ddd878a910ad5aa0bf61250f885c7a2b7) and click the update tenant button

**Comment by MatousJobanek** [comment]
Please let me know when you want to merge this PR. Because of testing a new logic of the tenant service that is still not in `master` branch, the [cico job](https://github.com/openshiftio/openshiftio-cico-jobs/blob/master/devtools-ci-index.yaml#L2922) is reconfigured to use `develop` branch for deploying to prod-preview. 
In order to test both your PR and the new tenant logic in prod-preview at the same time, then when this is merged to `master`, I'll need to either cherry-pick the commit or rebase it to `develop` branch

**Comment by rupalibehera** [comment]
LGTM :+1:

**Comment by fabric8cd** [comment]
This PR changes one or more of the template files. These changes are now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?templatesRepoBlob=b506f894b0ffa1d7a8c6579328fc029f3c4fc529) and click the update tenant button

**Comment by fabric8cd** [comment]
This PR changes one or more of the template files. These changes are now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?templatesRepoBlob=09ccc5c4fe289708a14b3f2dfa7b4d978a81186a) and click the update tenant button

**Comment by piyush-garg** [comment]
@MatousJobanek we are good to merge this PR

**Comment by fabric8cd** [comment]
This PR changes one or more of the template files. These changes are now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?templatesRepoBlob=25cb63dfb3349550eb2520683f115737487b9e36) and click the update tenant button

**Pull request merged**
