### PR TITLE
Clean PR creation code and update git repo path

### PR DESCRIPTION
**Pull request by vpavlin**
This should be merged once https://github.com/openshiftio/saas-openshiftio/ becomes active

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vpavlin snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-147-1`

**Comment by fabric8cd** [comment]
@vpavlin snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-147-3`

**Comment by fabric8cd** [comment]
@vpavlin snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-147-4`

**Comment by fabric8cd** [comment]
@vpavlin snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-147-5`

**Comment by fabric8cd** [comment]
@vpavlin snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-147-6`

**Comment by aslakknutsen** [comment]
[test]

**Pull request merged**
