### PR TITLE
make testing development YAML easier and get pipelines working on plain kubernetes

### PR DESCRIPTION
**Pull request by rawlingsj**
- add config to help test in development tenant YAML
- on kubernetes replace parameters to get pipelines pushing to docker registry

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-282-1`

**Comment by jstrachan** [comment]
[test] ok to test

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-282-3`

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-282-4`

**Pull request merged**
