### PR TITLE
break circular dependency between fabric8-platform and tenant-service

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-368-1`

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-368-2`

**Comment by jstrachan** [comment]
[test] add to whitelist

**Comment by jstrachan** [comment]
LGTM

**Pull request merged**
