### PR TITLE
fix(ODC-125): reorganization of the tenant namespaces

### PR DESCRIPTION
**Pull request by MatousJobanek**
The main changes are in templates stored in `environment/templates/` directory and in this [file](https://github.com/fabric8-services/fabric8-tenant/compare/master...MatousJobanek:remove-templates?expand=1#diff-548bfeebae84ae77e57356c9ba042b4aR34). The rest of the changes proposed in this PR are just their consequences (mainly in the tests).

fixes: https://jira.coreos.com/projects/ODC/issues/ODC-125

### CODE REVIEW

**Comment by fabric8cd** [comment]
This PR changes one or more of the template files. These changes are now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?templatesRepoBlob=2a025012b6e875ff8a882eef387d68cac872c977) and click the update tenant button

**Comment by MatousJobanek** [comment]
[test]

**Comment by fabric8cd** [comment]
This PR changes one or more of the template files. These changes are now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?templatesRepoBlob=2a025012b6e875ff8a882eef387d68cac872c977) and click the update tenant button

**Comment by alexeykazakov** [comment]
This PR is blocked by https://github.com/redhat-developer/rh-che/issues/1296 at the moment.

**Pull request merged**
