### PR TITLE
Refactor tenant service code (OSIO#2266)

### PR DESCRIPTION
**Pull request by xcoulon**
Moving all code from `token` into `auth`
Renaming some `Client` into `Service`
Moving generate auth client code in `auth/client`
Using some pointers here and there
Adapted some tests (using `require.Error(t, err)` and
`require.NoError(t, err)` when applicable)

Fixes #530 

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-530-1`

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-530-2`

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-530-3`

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-530-4`

**Comment by aslakknutsen** [comment]
The "keycloak" package should be split too. Both "PublicKeys" and "SA Helpers" are related to "token".

You can leave "keycloak/openshift" for now, but I suspect it will go next when we clean up which template vars are actually in use.

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-530-5`

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-530-6`

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-530-7`

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-530-8`

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-530-9`

**Comment by xcoulon** [comment]
thanks @aslakknutsen !

**Pull request merged**
