### PR TITLE
Verify the cluster tokens with a call to the `whoami` API #2383

### PR DESCRIPTION
**Pull request by xcoulon**
restored 'whoami' function and test with 'go-vcr'
refactored `whoami` and config, add tests
refactored the ClientOptions to use a common function (now in the `configuration` pkg) and fix the tests (using appropriate API urls and encrypted cluster token)

Fixes openshiftio/openshift.io#2383
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by xcoulon** [comment]
[test]

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-542-2`

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-542-3`

**Comment by xcoulon** [comment]
thanks @aslakknutsen !

**Pull request merged**
