### PR TITLE
Update Deployment Config API endpoints

### PR DESCRIPTION
**Pull request by l0rd**
This PR updates init-tenant to use Kubernetes Model 3.x. This is the model used in Che and Jenkins templates since [this PR](https://github.com/fabric8-services/fabric8-tenant-che/pull/61) that updates `fabric8-maven-plugin` to `v3.5.33` that include https://github.com/fabric8io/fabric8-maven-plugin/pull/1067:

```yaml
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
```

Incidentally this PR solves a failures to apply Che dc when initializing the \<user\>-che namespaces (users that logged in for the first time (c.f. https://github.com/openshiftio/openshift.io/issues/1448)):

```yaml
apiVersion: v1
code: 400
kind: Status
message: the API version in the data (apps.openshift.io/v1) does not match the expected API version
  (v1)
metadata: {}
reason: BadRequest
status: Failure
```

Jenkins was not affected because init-tenant still used an old version of the template. cc/ @jstrachan @rawlingsj @chmouel is it ok to update `JENKINS_VERSION` to `v4.0.43`?

### CODE REVIEW

**Comment by fabric8cd** [comment]
@l0rd snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-487-1`

**Comment by l0rd** [comment]
I am closing this PR since it looks like we cannot upgrade Jenkins to `v4.0.43` because of [this issue](https://github.com/openshiftio/openshift.io/issues/1254) caused by [a kubernetes-model regression](https://github.com/fabric8io/kubernetes-model/issues/241) when serializing timestamps. 

A new release of kubernetes-model [containing the fix](https://github.com/fabric8io/kubernetes-model/pull/242) has been released ([`v.2.0.4`](https://github.com/fabric8io/kubernetes-model/commits/v2.0.4)) but fabric8-tenant-jenkins still depends on version 1.0.67:

```
$ mvn dependency:tree
...
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ fabric8-tenant-jenkins-full ---
[INFO] io.fabric8.tenant.packages:fabric8-tenant-jenkins-full:jar:4.0.0-SNAPSHOT
[INFO] +- io.fabric8.tenant.apps:bayesian-link:jar:4.0.0-SNAPSHOT:compile
[INFO] +- io.fabric8.devops.apps:configmapcontroller:jar:2.2.335:compile
[INFO] +- io.fabric8.devops.apps:fabric8-docker-registry:jar:2.2.335:compile
[INFO] +- io.fabric8.devops.apps:hubot-mattermost:jar:2.2.335:compile
[INFO] |  +- io.fabric8:kubernetes-api:jar:2.2.205:compile
[INFO] |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  +- io.fabric8:openshift-client:jar:2.2.7:compile
[INFO] |  |  |  \- io.fabric8:kubernetes-client:jar:2.2.7:compile
[INFO] |  |  |     +- io.fabric8:kubernetes-model:jar:1.0.67:compile
[INFO] |  |  |     |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.7.4:compile
[INFO] |  |  |     +- com.squareup.okhttp3:okhttp:jar:3.6.0:compile
[INFO] |  |  |     |  \- com.squareup.okio:okio:jar:1.11.0:compile
[INFO] |  |  |     +- com.squareup.okhttp3:logging-interceptor:jar:3.6.0:compile
[INFO] |  |  |     +- org.slf4j:jul-to-slf4j:jar:1.7.12:compile
[INFO] |  |  |     +- com.fasterxml.jackson.core:jackson-databind:jar:2.7.4:compile
[INFO] |  |  |     |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.7.4:compile
[INFO] |  |  |     +- io.fabric8:zjsonpatch:jar:0.3.0:compile
[INFO] |  |  |     \- com.github.mifmif:generex:jar:1.0.1:compile
[INFO] |  |  |        \- dk.brics.automaton:automaton:jar:1.11-8:compile
[INFO] |  |  +- io.fabric8:fabric8-utils:jar:2.2.205:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.7.4:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.7.4:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.18:compile
[INFO] |  |  +- org.json:json:jar:20160212:compile
[INFO] |  |  +- dnsjava:dnsjava:jar:2.1.8:compile
[INFO] |  |  \- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO] |  \- io.fabric8:kubernetes-generator:jar:2.2.205:compile
[INFO] |     \- javax.inject:javax.inject:jar:1:compile
[INFO] +- io.fabric8.tenant.apps:jenkins:jar:4.0.0-SNAPSHOT:compile
[INFO] \- io.fabric8.devops.apps:nexus:jar:2.2.335:compile
...
```

**Comment by fabric8cd** [comment]
@l0rd snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-487-3`

**Comment by l0rd** [comment]
I have reopened the PR because Jenkins has also been updated to  use fabric8-maven-plugin v3.5.33. @rawlingsj @xcoulon can we merge this? It will solve https://github.com/openshiftio/openshift.io/issues/1519.

**Comment by fabric8cd** [comment]
@l0rd snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-487-4`

**Pull request merged**
