### PR TITLE
add a pipeline step to make sure the ci centos job has finished befor…

### PR DESCRIPTION
**Pull request by rawlingsj**
…e the fabric8 one starts

### CODE REVIEW

**Comment by rawlingsj** [comment]
Pretty sure this should work, basic tests do but won't know 100% until we try it on a release pipeline.

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-tenant image is available for testing.  `docker pull docker.io/fabric8/fabric8-tenant:SNAPSHOT-PR-401-1`

**Comment by rawlingsj** [comment]
[test]

**Comment by jstrachan** [comment]
[test]

**Comment by rawlingsj** [comment]
let's merge and see if it works.

**Comment by rawlingsj** [comment]
Yay! Worked first time :) https://jenkins.cd.test.fabric8.io/job/fabric8-services/job/fabric8-tenant/job/master/

**Pull request merged**
